<a href="https://colab.research.google.com/github/ahsanbulbul/chimera-pcbr/blob/main/Preprocessing_clinical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install awscli

In [ ]:
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Download the dataset into google drive (Do it once)

In [ ]:
# !ls "/content/drive/MyDrive"

Download directly to google drive

In [ ]:
# !aws s3 sync --no-sign-request s3://chimera-challenge/v2/task1/ "/content/drive/MyDrive/Chimera: Prostate Cancer Biochemical Recurrent Prediction/training_dataset_v1"

## Load the dataset

In [ ]:
dataset_path = "/content/drive/MyDrive/Chimera: Prostate Cancer Biochemical Recurrent Prediction/training_dataset_v1"

In [ ]:
files = os.listdir(dataset_path)
print(files)

['clinical_data', 'pathology', 'radiology', 'clinical_data.csv']

## Work with the clinical data

In [ ]:
import json
import pandas as pd
import os

In [ ]:
clinical_data_dir = os.path.join(dataset_path, "clinical_data")
files = os.listdir(clinical_data_dir)
print(files)

['1068.json', '1035.json', '1039.json', '1021.json', '1030.json', '1025.json', '1064.json', '1086.json', '1071.json', '1041.json', '1037.json', '1010.json', '1011.json', '1062.json', '1066.json', '1026.json', '1003.json', '1028.json', '1036.json', '1031.json', '1127.json', '1123.json', '1214.json', '1107.json', '1279.json', '1114.json', '1235.json', '1223.json', '1122.json', '1056.json', '1094.json', '1207.json', '1090.json', '1120.json', '1217.json', '1269.json', '1261.json', '1216.json', '1141.json', '1052.json', '1208.json', '1048.json', '1100.json', '1227.json', '1192.json', '1258.json', '1165.json', '1267.json', '1260.json', '1252.json', '1212.json', '1137.json', '1195.json', '1184.json', '1179.json', '1185.json', '1188.json', '1205.json', '1151.json', '1136.json', '1264.json', '1140.json', '1193.json', '1060.json', '1211.json', '1129.json', '1135.json', '1206.json', '1106.json', '1117.json', '1240.json', '1262.json', '1169.json', '1112.json', '1149.json', '1174.json', '1186.json', '1282.json', '1130.json', '1219.json', '1287.json', '1296.json', '1290.json', '1303.json', '1291.json', '1286.json', '1304.json', '1298.json', '1301.json', '1299.json', '1293.json', '1295.json', '1294.json', '1284.json', '1285.json']

### Convert json into csv (RUN IT ONCE)

In [ ]:
# data_list = []

# for file_name in files:
#     if file_name.endswith('.json'):
#         file_path = os.path.join(clinical_data_dir, file_name)
#         patient_id = os.path.splitext(file_name)[0]  # Extract patient ID from file name

#         try:
#             with open(file_path, 'r') as f:
#                 data = json.load(f)
#                 # Create a new dictionary with patient_id first
#                 ordered_data = {'patient_id': patient_id}
#                 ordered_data.update(data) # Add the rest of the data
#                 data_list.append(ordered_data)
#         except Exception as e:
#             print(f"Error processing file {file_name}: {e}")

In [ ]:
# # Create a pandas DataFrame from the list of dictionaries
# df = pd.DataFrame(data_list)

# Define the output CSV file path
output_csv_path = os.path.join(dataset_path, "clinical_data.csv")

# # Save the DataFrame to a CSV file
# df.to_csv(output_csv_path, index=False)

# print(f"CSV file created successfully at: {output_csv_path}")

### Import the csv

In [ ]:
clinical_data = pd.read_csv(output_csv_path)
clinical_data.head(50)

,patient_id,age_at_prostatectomy,primary_gleason,secondary_gleason,ISUP,pre_operative_PSA,BCR,time_to_follow-up/BCR,positive_lymph_nodes,capsular_penetration,positive_surgical_margins,invasion_seminal_vesicles,lymphovascular_invasion,earlier_therapy,tertiary_gleason,BCR_PSA
0,1068,58,3,3,1,2.11,0.0,60.2,x,0,0,0,0.0,none,NaN,NaN
1,1035,59,3,4,2,8.50,0.0,48.9,x,0,1,0,0.0,none,NaN,NaN
2,1039,63,3,4,2,13.90,0.0,2.9,0,0,0,0,0.0,none,NaN,NaN
3,1021,69,3,4,2,15.00,0.0,60.6,x,1,0,0,1.0,none,NaN,NaN
4,1030,86,4,3,3,24.90,1.0,2.6,0,1,1,1,1.0,none,5.0,0.8
5,1025,65,3,4,2,5.20,0.0,62.3,x,0,0,0,0.0,none,NaN,NaN
6,1064,72,4,3,3,3.30,1.0,36.7,1,0,0,0,1.0,none,NaN,0.1
7,1086,68,4,5,5,4.40,1.0,1.6,0,0,1,0,0.0,none,NaN,0.16
8,1071,56,3,4,2,13.50,0.0,56.4,x,0,0,0,0.0,unknown,NaN,NaN
9,1041,63,4,3,3,24.00,1.0,24.7,0,1,0,1,1.0,none,5.0,0.23
10,1037,68,3,4,2,8.10,0.0,63.1,0,1,0,0,0.0,none,NaN,NaN
11,1010,60,3,2,1,10.00,1.0,1.7,x,x,1,0,1.0,none,4.0,1.6
12,1011,66,4,3,3,6.90,0.0,60.7,x,0,0,0,0.0,none,NaN,NaN
13,1062,71,3,4,2,6.60,0.0,67.6,x,1,0,0,0.0,none,NaN,NaN
14,1066,67,4,3,3,4.60,0.0,56.1,x,0,1,0,0.0,none,NaN,NaN
15,1026,72,3,3,1,6.50,0.0,62.9,x,0,0,0,0.0,none,NaN,NaN
16,1003,66,3,4,2,8.30,1.0,1.3,1,1,1,1,1.0,none,5.0,0.11
17,1028,70,3,4,2,9.30,0.0,4.8,0,0,1,0,0.0,none,NaN,NaN
18,1036,61,3,4,2,3.90,0.0,57.1,0,1,1,0,0.0,none,5.0,NaN
19,1031,58,3,4,2,8.80,0.0,61.7,x,0,1,0,1.0,none,NaN,NaN
20,1127,72,4,3,3,7.60,1.0,14.9,x,1,1,0,0.0,none,NaN,0.3
21,1123,66,3,4,2,6.20,0.0,60.9,x,1,0,0,0.0,none,NaN,NaN
22,1214,62,4,3,3,160.00,1.0,11.4,0,1,1,0,1.0,none,5.0,0.12
23,1107,59,3,5,4,9.00,0.0,7.7,x,1,1,0,0.0,none,NaN,NaN
24,1279,59,4,3,3,6.20,0.0,35.4,0,1,0,0,0.0,none,NaN,NaN
25,1114,55,3,3,1,6.90,0.0,63.1,x,0,1,0,0.0,none,NaN,NaN
26,1235,64,4,3,3,9.50,0.0,34.7,x,0,0,0,0.0,none,NaN,NaN
27,1223,67,3,4,2,15.80,0.0,47.7,0,0,0,0,0.0,none,5.0,NaN
28,1122,56,5,4,5,12.00,1.0,1.5,1,x,1,0,0.0,none,NaN,0.1
29,1056,56,5,3,4,4.50,0.0,80.8,x,0,1,0,0.0,none,NaN,NaN
30,1094,54,3,3,1,0.20,0.0,65.7,x,0,1,0,0.0,none,4.0,NaN
31,1207,57,4,5,5,7.80,0.0,43.1,0,1,1,1,1.0,none,NaN,NaN
32,1090,73,4,5,5,68.00,1.0,1.5,1,1,1,1,1.0,none,3.0,0.28
33,1120,63,3,4,2,12.00,0.0,54.1,0,0,1,0,0.0,none,NaN,NaN
34,1217,67,3,4,2,5.00,1.0,19.2,0,0,0,0,0.0,none,NaN,0.14
35,1269,70,3,4,2,11.40,0.0,49.6,x,0,0,0,0.0,none,NaN,NaN
36,1261,66,4,3,3,5.80,0.0,38.5,x,0,1,0,0.0,none,5.0,NaN
37,1216,67,3,4,2,4.80,0.0,38.0,x,0,0,0,0.0,none,NaN,NaN
38,1141,64,3,4,2,8.30,0.0,62.5,x,1,1,0,0.0,none,NaN,NaN
39,1052,57,3,3,2,7.00,0.0,65.0,x,0,1,0,0.0,none,NaN,NaN
40,1208,73,4,3,3,86.00,1.0,1.8,1,1,1,1,0.0,none,NaN,0.2
41,1048,51,3,4,2,8.40,0.0,23.7,x,0,0,0,0.0,none,NaN,NaN
42,1100,65,4,4,4,7.90,1.0,2.0,0,0,0,0,1.0,none,NaN,0.17
43,1227,63,4,3,3,18.00,0.0,24.2,x,0,0,0,0.0,none,NaN,NaN
44,1192,65,4,4,3,8.60,0.0,63.1,0,0,1,0,1.0,none,NaN,NaN
45,1258,70,4,3,3,12.00,1.0,4.4,0,1,1,1,0.0,none,5.0,0.17
46,1165,60,4,5,5,16.80,1.0,1.8,0,1,1,1,1.0,radiotherapy + cryotherapy,NaN,1.2
47,1267,73,3,4,2,7.93,0.0,35.5,x,0,1,0,0.0,none,NaN,NaN
48,1260,72,3,4,2,4.10,0.0,37.0,1,0,1,0,0.0,none,NaN,NaN
49,1252,65,4,3,4,11.00,0.0,47.1,x,0,0,0,0.0,none,NaN,NaN

### Handle null values

In [ ]:
# find the null values
clinical_data.isnull().sum()

patient_id                    0
age_at_prostatectomy          0
primary_gleason               0
secondary_gleason             0
ISUP                          0
pre_operative_PSA             0
BCR                           0
time_to_follow-up/BCR         0
positive_lymph_nodes          0
capsular_penetration          0
positive_surgical_margins     0
invasion_seminal_vesicles     0
lymphovascular_invasion       0
earlier_therapy               0
tertiary_gleason             75
BCR_PSA                      67
dtype: int64

In [ ]:
# drop the columns tertiary_gleason and BCR_PSA
clinical_data = clinical_data.drop(['tertiary_gleason', 'BCR_PSA'], axis=1)

### Normalization

In [ ]:
cols_to_normalize = ['age_at_prostatectomy', 'pre_operative_PSA', 'time_to_follow-up/BCR']

clinical_data[cols_to_normalize] = (clinical_data[cols_to_normalize] - clinical_data[cols_to_normalize].mean()) / clinical_data[cols_to_normalize].std()

### Handling Positive lymph nodes
- here 'x' simply means the lymph nodes were removed during surgery
- treat it as different category with value 2

In [ ]:
# find the ratio of present 'x' in the column positive_lymph_nodes

x_count = (clinical_data['positive_lymph_nodes'] == 'x').sum()
total_count = len(clinical_data)
x_ratio = x_count / total_count

print(f"The ratio of 'x' in 'positive_lymph_nodes' is: {x_ratio}")

The ratio of 'x' in 'positive_lymph_nodes' is: 0.5578947368421052

In [ ]:
# print the unique records in the column positive_lymph_nodes
print(clinical_data['positive_lymph_nodes'].unique())

['x' '0' '1']

In [ ]:
# replace 'x' by 2
clinical_data['positive_lymph_nodes'] = clinical_data['positive_lymph_nodes'].replace('x', 2)

### Handling earlier_therapy

In [ ]:
print(clinical_data['earlier_therapy'].unique())

['none' 'unknown' 'radiotherapy + cryotherapy' 'radiotherapy + hormones']

In [ ]:
import re

In [ ]:
### Step 1: Extract atomic therapies ###
def extract_atoms(therapy_str: str) -> list:
    """Splits therapy string into atomic components."""
    if therapy_str.lower().strip() in ['none', 'unknown', '', None]:
        return []
    return re.split(r'\s*\+\s*', therapy_str.lower().strip())

In [ ]:
### Step 2: Build vocabulary ###
def build_therapy_vocab(therapy_series: pd.Series) -> list:
    """Build vocabulary of atomic therapies."""
    atom_set = set()
    for entry in therapy_series:
        atom_set.update(extract_atoms(entry))
    return sorted(atom_set)

therapy_vocab = build_therapy_vocab(clinical_data['earlier_therapy'])
print("Therapy Vocabulary:", therapy_vocab)

Therapy Vocabulary: ['cryotherapy', 'hormones', 'radiotherapy']

In [ ]:
### Step 3: Multi-hot encode each entry ###
def multi_hot_encode(therapy_str: str, vocab: list) -> list:
    """Multi-hot encodes a single therapy string."""
    atoms = extract_atoms(therapy_str)
    return [1 if v in atoms else 0 for v in vocab]

In [ ]:
# Apply encoding
clinical_data['therapy_vector'] = clinical_data['earlier_therapy'].apply(
    lambda x: multi_hot_encode(x, therapy_vocab)
)

Convert therapy vector from list to numerical list

In [ ]:
import numpy as np
import torch

In [ ]:
therapy_matrix = np.stack(clinical_data['therapy_vector'].values)
therapy_tensor = torch.tensor(therapy_matrix, dtype=torch.float)

In [ ]:
clinical_data.drop(columns='earlier_therapy', inplace=True)
clinical_data = clinical_data.rename(columns={'therapy_vector': 'earlier_therapy'})

clinical_data.head(50)

,patient_id,age_at_prostatectomy,primary_gleason,secondary_gleason,ISUP,pre_operative_PSA,BCR,time_to_follow-up/BCR,positive_lymph_nodes,capsular_penetration,positive_surgical_margins,invasion_seminal_vesicles,lymphovascular_invasion,earlier_therapy
0,1068,-1.054517,3,3,1,-0.446714,0.0,0.963574,2,0,0,0,0.0,"[0, 0, 0]"
1,1035,-0.896506,3,4,2,-0.204518,0.0,0.486959,2,0,1,0,0.0,"[0, 0, 0]"
2,1039,-0.264461,3,4,2,0.000156,0.0,-1.453241,0,0,0,0,0.0,"[0, 0, 0]"
3,1021,0.683607,3,4,2,0.041848,0.0,0.980445,2,1,0,0,1.0,"[0, 0, 0]"
4,1030,3.369799,4,3,3,0.417082,1.0,-1.465894,0,1,1,1,1.0,"[0, 0, 0]"
5,1025,0.051562,3,4,2,-0.329596,0.0,1.052148,2,0,0,0,0.0,"[0, 0, 0]"
6,1064,1.157641,4,3,3,-0.401610,1.0,-0.027616,1,0,0,0,1.0,"[0, 0, 0]"
7,1086,0.525595,4,5,5,-0.359918,1.0,-1.508073,0,0,1,0,0.0,"[0, 0, 0]"
8,1071,-1.370540,3,4,2,-0.015005,0.0,0.803296,2,0,0,0,0.0,"[0, 0, 0]"
9,1041,-0.264461,4,3,3,0.382970,1.0,-0.533755,0,1,0,1,1.0,"[0, 0, 0]"
10,1037,0.525595,3,4,2,-0.219679,0.0,1.085891,0,1,0,0,0.0,"[0, 0, 0]"
11,1010,-0.738495,3,2,1,-0.147664,1.0,-1.503855,2,x,1,0,1.0,"[0, 0, 0]"
12,1011,0.209573,4,3,3,-0.265162,0.0,0.984663,2,0,0,0,0.0,"[0, 0, 0]"
13,1062,0.999629,3,4,2,-0.276532,0.0,1.275693,2,1,0,0,0.0,"[0, 0, 0]"
14,1066,0.367584,4,3,3,-0.352337,0.0,0.790643,2,0,1,0,0.0,"[0, 0, 0]"
15,1026,1.157641,3,3,1,-0.280322,0.0,1.077455,2,0,0,0,0.0,"[0, 0, 0]"
16,1003,0.209573,3,4,2,-0.212098,1.0,-1.520726,1,1,1,1,1.0,"[0, 0, 0]"
17,1028,0.841618,3,4,2,-0.174196,0.0,-1.373102,0,0,1,0,0.0,"[0, 0, 0]"
18,1036,-0.580484,3,4,2,-0.378869,0.0,0.832821,0,1,1,0,0.0,"[0, 0, 0]"
19,1031,-1.054517,3,4,2,-0.193147,0.0,1.026841,2,0,1,0,1.0,"[0, 0, 0]"
20,1127,1.157641,4,3,3,-0.238630,1.0,-0.947102,2,1,1,0,0.0,"[0, 0, 0]"
21,1123,0.209573,3,4,2,-0.291693,0.0,0.993098,2,1,0,0,0.0,"[0, 0, 0]"
22,1214,-0.422472,4,3,3,5.537703,1.0,-1.094726,0,1,1,0,1.0,"[0, 0, 0]"
23,1107,-0.896506,3,5,4,-0.185566,0.0,-1.250785,2,1,1,0,0.0,"[0, 0, 0]"
24,1279,-0.896506,4,3,3,-0.291693,0.0,-0.082447,0,1,0,0,0.0,"[0, 0, 0]"
25,1114,-1.528551,3,3,1,-0.265162,0.0,1.085891,2,0,1,0,0.0,"[0, 0, 0]"
26,1235,-0.106450,4,3,3,-0.166615,0.0,-0.111972,2,0,0,0,0.0,"[0, 0, 0]"
27,1223,0.367584,3,4,2,0.072170,0.0,0.436345,0,0,0,0,0.0,"[0, 0, 0]"
28,1122,-1.370540,5,4,5,-0.071859,1.0,-1.512291,1,x,1,0,0.0,"[0, 0, 0]"
29,1056,-1.370540,5,3,4,-0.356127,0.0,1.832446,2,0,1,0,0.0,"[0, 0, 0]"
30,1094,-1.686563,3,3,1,-0.519108,0.0,1.195554,2,0,1,0,0.0,"[0, 0, 0]"
31,1207,-1.212529,4,5,5,-0.231049,0.0,0.242325,0,1,1,1,1.0,"[0, 0, 0]"
32,1090,1.315652,4,5,5,2.050678,1.0,-1.512291,1,1,1,1,1.0,"[0, 0, 0]"
33,1120,-0.264461,3,4,2,-0.071859,0.0,0.706286,0,0,1,0,0.0,"[0, 0, 0]"
34,1217,0.367584,3,4,2,-0.337176,1.0,-0.765735,0,0,0,0,0.0,"[0, 0, 0]"
35,1269,0.841618,3,4,2,-0.094601,0.0,0.516484,2,0,0,0,0.0,"[0, 0, 0]"
36,1261,0.209573,4,3,3,-0.306854,0.0,0.048305,2,0,1,0,0.0,"[0, 0, 0]"
37,1216,0.367584,3,4,2,-0.344757,0.0,0.027216,2,0,0,0,0.0,"[0, 0, 0]"
38,1141,-0.106450,3,4,2,-0.212098,0.0,1.060584,2,1,1,0,0.0,"[0, 0, 0]"
39,1052,-1.212529,3,3,2,-0.261371,0.0,1.166029,2,0,1,0,0.0,"[0, 0, 0]"
40,1208,1.315652,4,3,3,2.732922,1.0,-1.499637,1,1,1,1,0.0,"[0, 0, 0]"
41,1048,-2.160596,3,4,2,-0.208308,0.0,-0.575933,2,0,0,0,0.0,"[0, 0, 0]"
42,1100,0.051562,4,4,4,-0.227259,1.0,-1.491201,0,0,0,0,1.0,"[0, 0, 0]"
43,1227,-0.264461,4,3,3,0.155556,0.0,-0.554844,2,0,0,0,0.0,"[0, 0, 0]"
44,1192,0.051562,4,4,3,-0.200727,0.0,1.085891,0,0,1,0,1.0,"[0, 0, 0]"
45,1258,0.841618,4,3,3,-0.071859,1.0,-1.389974,0,1,1,1,0.0,"[0, 0, 0]"
46,1165,-0.738495,4,5,5,0.110073,1.0,-1.499637,0,1,1,1,1.0,"[1, 0, 1]"
47,1267,1.315652,3,4,2,-0.226122,0.0,-0.078230,2,0,1,0,0.0,"[0, 0, 0]"
48,1260,1.157641,3,4,2,-0.371288,0.0,-0.014962,1,0,1,0,0.0,"[0, 0, 0]"
49,1252,0.051562,4,3,4,-0.109761,0.0,0.411038,2,0,0,0,0.0,"[0, 0, 0]"

### Save the cleaned data in drive

In [ ]:
# prompt: save the cleaned dataset as csv inside drive

# Define the output CSV file path for the cleaned data
cleaned_output_csv_path = os.path.join(dataset_path, "clinical_data_cleaned.csv")

# Save the cleaned DataFrame to a CSV file
clinical_data.to_csv(cleaned_output_csv_path, index=False)

print(f"Cleaned CSV file created successfully at: {cleaned_output_csv_path}")

Cleaned CSV file created successfully at: /content/drive/MyDrive/Chimera: Prostate Cancer Biochemical Recurrent Prediction/training_dataset_v1/clinical_data_cleaned.csv